/**
* File generated by the command `npm run switch-init`
* @component @dsia/boilerplate
*/

/// @from src
export * from '../../projects/dsia-boilerplate/src/public_api';

/// @from dist
// export * from '../../../../dist-lib/boilerplate';

/// @from node_modules
// export * from '@dsia/boilerplate';
